quarkus.application.name=careflow-api
quarkus.http.port=${PORT:8080}
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.smallrye-health.root-path=/q/health
quarkus.log.category."com.skyyware.careflow".level=INFO
