quarkus.application.name=careflow-api
quarkus.http.port=${PORT:8080}
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.smallrye-health.root-path=/q/health
quarkus.log.category."com.skyyware.careflow".level=INFO
quarkus.mailer.from=${QUARKUS_MAILER_FROM:admin@stage.dev}
app.registration.notify-to=${APP_REGISTRATION_NOTIFY_TO:admin@stage.dev}
